### PR TITLE
new UI developed, bugs solved

### PR DESCRIPTION
**Pull request by KanishkVijaywargiya**

### CODE REVIEW

**Comment by djm-1** [comment]
Nice Work 👍

**Comment by KanishkVijaywargiya** [comment]
*Hi* Dibyajyoti Mondal,

Thanks for appreciating my work.
Do you also build apps on the iOS platform using SwiftUI ?

Regards,
Kanishk Vijaywargiya

**Comment by KanishkVijaywargiya** [comment]
Please check out one of my app developed in swiftUI.

https://www.linkedin.com/feed/update/urn:li:activity:6847232981766082560/

https://www.linkedin.com/posts/kanishk-vijaywargiya-b21a98153_iosdevelopment-iosdevelopers-iosengineer-activity-6847232981766082560-ZDVK

**Comment by djm-1** [comment]
Hi Kanishk,

I have checked out your app. It's really cool. The UI looks great. But, I'm not into android/ios development yet. I am mainly a full-stack developer.

**Comment by KanishkVijaywargiya** [comment]
Hey Hi,
Are you on Linkedln ? Which Tech stack u used full stack development eg
MERN or DJango?

**Comment by djm-1** [comment]
My LinkedIn Profile: https://www.linkedin.com/in/dibyajyoti-mondal-8632991a0/
I'm a Django developer. Now I'm learning React.

Check out my blog: https://www.djmblogs.ml/

**Pull request merged**
